### ISSUE TITLE
How to use promotion code?

### ISSUE THREAD

**Issue by nmhung89** [eventespresso/EE4-Promotions#1]
Hi,

I am using EE4 version  4.8.1.beta.001 and EE4-Promotions at commit #1464426 - this is the newest version which I can use with my current EE4 core. I can see page Event Espresso > Add-ons > Promotion to manage and create new promotions. However, I don't know how to apply it to my new created Event. As I search from some sources, It should have had a setting in Event Espresso > Settings > General Settings to enable promotion code feature for events but I couldn't find out it. Please guide.

Thanks

**Comment by joshfeck** [comment]
Hi there,

It turns out there is no such setting in Event Espresso 4. You can set an event to use a promo code from within the promo code editor's **Promotion applies to...** box.

![promotion-applies-to](https://cloud.githubusercontent.com/assets/891156/9060641/a050ba0a-3a83-11e5-92d5-959d0f622a0e.png)

**Comment by sethshoultes** [comment]
We should add this as a feature request, if there isn't one already, to add codes from within the event. I think that makes sense, because otherwise after you create an event, you have to go back in and apply each discount to an event.

**Comment by nerrad** [comment]
What is the feature request you see here?

**Comment by sethshoultes** [comment]
The ability to assign discount codes to an event,  from within the event.

**Comment by joshfeck** [comment]
ticket #8606

**Comment by nmhung89** [comment]
Thank you for your reply, I saw that setting and have checked on the event already. Does it suppose to show a text field in payment page for user to enter the promotion code? Or what should I do to create a text field like that using this plugin?

**Comment by joshfeck** [comment]
Yes, when the promotions add-on is active, it adds a promotional code input field with a submit button in between the table that shows the registration tickets info and the selectable payment method. It looks like this:

![promo-code-field](https://cloud.githubusercontent.com/assets/891156/9067113/93f4e8b4-3aa9-11e5-8b8a-a2c1f198185f.png)

If you do not see the field with the Promotions add-on activated, a good troubleshooting step that you can try is deactivate all other plugins and temporarily switch to a default WordPress theme.

**Comment by nmhung89** [comment]
Ah ok, thank you for your quick answer, you made my day. I am quite new to wordpress and have just received this project from a run-away developer, I just want to make sure that the plugin has this feature for troubleshooting :)
