### ISSUE TITLE
Populate Promo Code Based on URL

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/EE4-Promotions#11]
This would allow a user that lands at an event page (or event list filtered for events that the promo code is good for) and the promo code gets saved to the session for use later if they start the reg process.

For reference:
https://eventespresso.com/topic/automatic-promo-code/
https://secure.helpscout.net/conversation/637470597/555888/
https://github.com/eventespresso/EE4-Promotions/issues/11

**Comment by mnelson4** [comment]
cool

**Comment by sethshoultes** [comment]
Thanks for digging that one up Garth. Updated that old CB ticket.
