### ISSUE TITLE
Promotions config not set until settings visited

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/EE4-Promotions#17]
If you activate the promotions add-on and straight from there go to Promotions -> Add new and add a new promo  (either global or event specific).

When you register onto an event 2 notices are thrown:

PHP Notice:  Trying to get property of non-object in /wp-content/plugins/EE4-Promotions/EED_Promotions.module.php on line 549

PHP Notice:  Trying to get property of non-object in/wp-content/plugins/EE4-Promotions/EED_Promotions.module.php on line 561

Looks like it's for labels used on the Promotions inputs.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Steps to Reproduce (for bugs)
Clean install, active EE4 core and the promotions add-on.

Create an event, create a promotion (don't visit other tabs in the promotion add-on).

Register onto the event.

Not critical and the fix is simple, visit the promotions setting page but shouldn't that be set already?

**Comment by joshfeck** [comment]
This would actually explain some of the weirdness we used to see before which led to the fallback added in https://events.codebasehq.com/projects/event-espresso/tickets/10892.

@Pebblo is this something you can fix? If so please do a PR and send to Brent for review.

**Comment by raphaelkross** [comment]
@Pebblo @joshfeck @tn3rb I freshly installed EE4-Promotions, never visited the Settings page but not being able to reproduce this issue at my end.

May you confirm it still happens? The access to the label variables seems to happen without problems / defaults are also set at EE_Promotions_Config on the init event.

**Comment by joshfeck** [comment]
Can you check this again @Pebblo ?

**Comment by Pebblo** [comment]
Checked over this again and couldn't get the notices to throw again.

I then tested #21 whilst there and merged that in.

So for now, I'm closing this out.

Thanks @raphaelkross
