### ISSUE TITLE
Convert `[ESPRESSO_PROMOTIONS]` shortcode to gutenberg block

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/EE4-Promotions#2]
@sethshoultes commented on [Fri Apr 27 2018](https://github.com/eventespresso/event-espresso-core/issues/368)

Codebase https://events.codebasehq.com/projects/event-espresso/tickets/11434

---

@ee-duplicate-ticket-detector[bot] commented on [Fri Apr 27 2018](https://github.com/eventespresso/event-espresso-core/issues/368#issuecomment-385075465)

Potential duplicates: 
- [#367] Convert &#x60;[ESPRESSO_CALENDAR]&#x60; shortcode to gutenberg block (91%) 
- [#366] Convert &#x60;[ESPRESSO_MY_EVENTS]&#x60; shortcode to Gutenberg block (92%) 
- [#365] Convert &#x60;[ESPRESSO_BARCODE_SCANNER]&#x60; shortcode to gutenberg (74%) 
- [#364] Convert &#x60;[ESPRESSO_TICKET_SELECTOR]&#x60; to Gutenberg block (72%) 
- [#363] Convert &#x60;[ESPRESSO_EVENTS]&#x60; shortcode to gutenberg block. (89%) 

---

@ee-duplicate-ticket-detector[bot] commented on [Fri Apr 27 2018](https://github.com/eventespresso/event-espresso-core/issues/368#issuecomment-385075469)

Potential duplicates: 
- [#367] Convert &#x60;[ESPRESSO_CALENDAR]&#x60; shortcode to gutenberg block (91%) 
- [#366] Convert &#x60;[ESPRESSO_MY_EVENTS]&#x60; shortcode to Gutenberg block (92%) 
- [#365] Convert &#x60;[ESPRESSO_BARCODE_SCANNER]&#x60; shortcode to gutenberg (74%) 
- [#364] Convert &#x60;[ESPRESSO_TICKET_SELECTOR]&#x60; to Gutenberg block (72%) 
- [#363] Convert &#x60;[ESPRESSO_EVENTS]&#x60; shortcode to gutenberg block. (89%)

**Comment by joshfeck** [comment]
I don't think the promotions shortcode gets enough use or has any requested features to warrant converting it into a block.
