### ISSUE TITLE
Add input field for setting PRO_global_uses

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/EE4-Promotions#26]
The `esp_promotion` table has a `PRO_global_uses` column and there’s logic that enforces the limit set to that field for the promotion. There's just no UI to set the value.

For example: If `PRO_global_uses` gets set to 1, then a promo code set to Apply Promo to ALL Scope Items (events) can be used one time for just one event (instead of one time for one event, then one time for another event and so on). 

- [ ] add the input to `\Promotions_Admin_Page::promotion_details_metabox()`

- [ ] then capture value and save it in `\Promotions_Admin_Page::_insert_update_promotions()`

**Comment by Pebblo** [comment]
This was done in #27
