### ISSUE TITLE
Only display promo code field if there's an event in the cart that accepts promotion codes

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/EE4-Promotions#5]
See original Codebase ticket:
https://events.codebasehq.com/projects/event-espresso/tickets/10662

Can we make Promotions smarter so that if a promotion does not apply to an event, the promo field does not show in the checkout? Only show the coupon field for events with applicable promotions.

@Pebblo created a snippet, which we think should be included on Event Smart:
https://gist.github.com/Pebblo/d66550019e101a65b021a6fff5ed5c21

@tn3rb's concerns:

> just an FYI, that dynamically turning the promo code field off and on based on if there are active promo codes will slow things down because we will have to do a bunch of querying to determine if there are any active codes for the events that are currently in the cart.
From my experience, nearly every online checkout I have seen has had a field for entering promo codes.
Not sure why it's such an issue for people that our checkout has one too.

@garthkoyle's reply:

> We intentionally hide the promotion code field with EventEspresso.com and EventSmart.com because it causes people to abandon the cart and go looking for a promotion code (even if there is not one available). I don't think it's a very good business practice to show the promotion code field unnecessarily.

**Comment by sethshoultes** [comment]
@tn3rb can we revisit this issue?

**Comment by garthkoyle** [comment]
uh, please don't close this.

**Comment by tn3rb** [comment]
hmmmm not sure why I initially thought this was going to be more complex than it likely is...

## required steps and time estimates

- (1 hour) add `$this` as an extra params to the `FHEE__EE_SPCO_Reg_Step_Payment_Options___display_payment_options__before_payment_options` filter (maybe to some of the other hooks in that class as well if they don't already include it)
- (2 hours) in `EED_Promotions::_add_promotions_form_inputs()`, extract list of events for tickets in current cart then perform count query for promotion codes that are applicable to that event. If result is `0`, then do not show promo code input field in checkout

**Comment by lorenzocaum** [comment]
+1 for adding this. Within the past month, a few new event organizers on Event Smart have asked about it while under trial and each time I've let them know that it will go away after their trial wraps up in a few days.

As a side note, I remember seeing some conversion research that one way to handle promotions is to put it behind a link that expands to show the field if you click it. 

Then people are less likely to click away and go searching for a promotion code while those that do have one, can still use it.

**Comment by joshfeck** [comment]
When we do this we should add a filter hook to allow site owners to add a simple filter function so they can opt out where the site can continue to have the existing behavior.

**Comment by Pebblo** [comment]
Fixed in #22
